Update bhnet.py
 echo -ne "GET / HTTP/1.1\r\nHost: www.google.com\r\n\r\n" | ./bhnet.py -t www.google.com -p 80
Traceback (most recent call last):
  File "./bhnet.py", line 239, in <module>
    main()

encoding buffer fixed it for me :)
  File "./bhnet.py", line 230, in main
    client_sender(buffer)
  File "./bhnet.py", line 127, in client_sender
    client.send(buffer)
TypeError: a bytes-like object is required, not 'str'